/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRequestsRouteImport } from './routes/service-requests'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as IndexRouteImport } from './routes/index'

const ServiceRequestsRoute = ServiceRequestsRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/service-requests': typeof ServiceRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/service-requests': typeof ServiceRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/service-requests': typeof ServiceRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dispatch' | '/service-requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dispatch' | '/service-requests'
  id: '__root__' | '/' | '/dispatch' | '/service-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispatchRoute: typeof DispatchRoute
  ServiceRequestsRoute: typeof ServiceRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-requests': {
      id: '/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof ServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispatchRoute: DispatchRoute,
  ServiceRequestsRoute: ServiceRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
